[project]
name = "stackoverflowchallenges"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "networkx>=3.6.1",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "pandas-stubs~=3.0.3",
    "requests>=2.32.5",
    "scipy>=1.17.0",
]
